server:
  port: 8888
spring:
  application:
    name: im-platform
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boxim?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: boxim
    password: 123456
  redis:
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations:
    - classpath*:mapper/*.xml
minio:
  endpoint: http://127.0.0.1:9090
  public: http://43.129.193.243:9090
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video
webrtc:
  iceServers: #coturn配置
    - urls: stun:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
    - urls: turn:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
jwt:
  accessToken:
    expireIn: 28800  #半个小时
    secret: ztcv8qKGHV
  refreshToken:
    expireIn: 604800 #7天
    secret: g2VnugZYLw
logging:
  config: classpath:logback-prod.xml
ip:
  url: http://ip-api.com/json/